"""add unique index to vacancy url

Revision ID: 257781351b2f
Revises: 39d0e806d3d3
Create Date: 2026-08-04 14:32:32.895943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257781351b2f'
down_revision: Union[str, Sequence[str], None] = '39d0e806d3d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vacancies_url'), 'vacancies', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_url'), table_name='vacancies')
    # ### end Alembic commands ###
