"""add resume_text to users

Revision ID: 3bcaaeefb601
Revises: 1c695ef0616e
Create Date: 2026-07-21 13:16:55.341706

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3bcaaeefb601"
down_revision: Union[str, Sequence[str], None] = "1c695ef0616e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("resume_text", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "resume_text")
    # ### end Alembic commands ###
